name: Feature branch stuff
on: 
  push: 
    branches: 
      - 'feature/*'
    paths-ignore:
      - '*Dockerfile*'
      
jobs:
  
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buduje mosty dla Pana Starosty!"
  
  UT:
    name: Unit Tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testuje mosty dla Pana Starosty!"

  lint:
    name: Lint the code
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lintujemy mosty dla Pana Starosty!"
    
