name: PR to main pipe

on:
  pull_request:
    branches: 
      - main
    types: 
      - opened
  push:
    branches:
      - main
      
jobs:
  
  squash:
    name: Squashin smashin commits
    runs-on: ubuntu-latest
    steps:
      - run: echo "Squash me baby!"
